Add type Disc and discs collection
Guiblasco/music-oasis-crafters pull request #1
Opened 2024-07-16 17:54 UTC by Guiblasco

Added a new type named Disc and create a new discs collection
Uninstall serve from prod dependecies and install now Typescript and Serve to Dev dependencies.

2024-07-16 18:08 UTC, the-refactor-project requested changes

2024-07-16 18:08 UTC, the-refactor-project commented on package.json
> +  "main": "public/js/index.js",
Si el JS va a ser ejecutado por un browser, esta propiedad del `package.json` no fa res.

2024-07-16 18:08 UTC, the-refactor-project commented on src/types.ts
> +  image: string;
¿Esta propiedad va a almacenar "una imagen"?

2024-07-16 18:08 UTC, the-refactor-project commented on src/types.ts
> +  discFormat: string;
¿Aquí podrá ir cualquier string?

2024-07-16 18:08 UTC, the-refactor-project commented on src/types.ts
> +  pirce: number;
Errata.

2024-07-16 18:08 UTC, the-refactor-project commented on src/types.ts
> +  isMonthDisc: boolean;
Este nombre no es correcto en inglés.

2024-07-16 18:08 UTC, the-refactor-project commented on src/types.ts
> +  originalPrice: number;
Ordenad las propiedades de manera que las que estén relacionadas entre sí vayan juntas.

2024-07-16 18:08 UTC, the-refactor-project commented on src/data.ts
> +const discsCollection: Disc[] = [];
**INTRO fuerte**

2024-07-16 18:08 UTC, the-refactor-project commented on src/data.ts
> +const discsCollection: Disc[] = [];
¿Qué va a almacenar esa variable?

2024-07-16 21:01 UTC, the-refactor-project commented on src/types.ts
> +  isMonthDisc: boolean;
Eso significaría "disco mensual", que tampoco es correcto.

2024-07-16 21:01 UTC, the-refactor-project commented on src/data.ts
> +const discsCollection: Disc[] = [];
No hablo de JS, hablo de qué representa el valor que va a almacenar.

2024-07-17 07:02 UTC, Guiblasco commented on src/data.ts
> +const discsCollection: Disc[] = [];
objetos tipo `Disc`

2024-07-17 10:34 UTC, the-refactor-project commented on src/data.ts
> +const discsCollection: Disc[] = [];
Si yo digo que no hablo de código, sino de qué representa un valor, no me podéis dar una respuesta de código.

2024-07-17 12:57 UTC, Guiblasco commented on src/types.ts
> +  discFormat: string;
probé el `union type` pero ahora lo he puesto en que acepte solo dos valores `"CD" | "Digital"`

2024-07-17 12:57 UTC, Guiblasco commented on src/types.ts
> +  pirce: number;
ups! estoy revisando el archivo! ty

2024-07-17 12:59 UTC, Guiblasco commented on src/types.ts
> +  originalPrice: number;
perfect! ahora lo miro

2024-07-17 12:59 UTC, Guiblasco commented on src/data.ts
> +const discsCollection: Disc[] = [];
muy fuerte!

2024-07-17 13:01 UTC, Guiblasco commented on src/data.ts
> +const discsCollection: Disc[] = [];
Discos? sii, lo hemos hablado antes, una collecion de discos `array` es simplemente `discs`

2024-07-17 13:05 UTC, Guiblasco commented on src/types.ts
> +  image: string;
hecho!

2024-07-17 13:06 UTC, the-refactor-project commented on src/types.ts
> +  isMonthDisc: boolean;
![image](https://github.com/user-attachments/assets/b8c7acd0-12d6-4fdb-835c-21fc7c3abd0d)

2024-07-17 13:06 UTC, the-refactor-project commented on src/data.ts
> +const discsCollection: Disc[] = [];
Molt millor.

2024-07-17 18:48 UTC, lexisgasa approved these changes

2024-07-17 18:49 UTC, merged

2024-07-17 19:08 UTC, the-refactor-project commented on package.json
> +  "main": "public/js/index.js",
@Guiblasco no tengo feedback de este comentario

2024-07-17 19:18 UTC, Guiblasco commented on package.json
> +  "main": "public/js/index.js",
tienes razón, no hace falta la carpeta `js`

2024-07-17 19:20 UTC, the-refactor-project commented on package.json
> +  "main": "public/js/index.js",
Lee bien mi comentario: lo que no fa res es **la propiedad**

2024-07-17 19:21 UTC, Guiblasco commented on package.json
> +  "main": "public/js/index.js",
adios.... ya no se ni lo que ven mis ojos, si estoy en el mundo real o una especie de matrix

2024-07-17 19:26 UTC, the-refactor-project commented on package.json
> +  "main": "public/js/index.js",
Nunca lo sabrás (muahaHAHAHAHA)