Create disc type and an array disc, and fix package.json
Guiblasco/music-oasis-crafters pull request #3
Opened 2024-07-17 19:16 UTC by Guiblasco

Fix tpyed erros
- naming variables fixed
- package.json fixed

2024-07-17 19:29 UTC, the-refactor-project requested changes

2024-07-17 19:29 UTC, the-refactor-project commented on package.json
> +  "main": "public/index.js",
Este archivo no existe, y además esta propiedad no hace nada cuando nuestra aplicación es ejecutada en un browser.

2024-07-17 19:29 UTC, the-refactor-project commented on src/types.ts
>    isMonthDisc: boolean;
Este nombre sigue siendo incorrecto y no se ha implementado la propuesta de nombre de la otra PR.

2024-07-18 07:42 UTC, lexisgasa commented on src/types.ts
>    isMonthDisc: boolean;
la propuesta era `isDiscOfTheMonth`, que creo que es más descriptivo Guillem

2024-07-18 17:31 UTC, Guiblasco commented on package.json
> +  "main": "public/index.js",
entendido!! no ejecuta mi equipo sino netlify

2024-07-18 17:31 UTC, Guiblasco commented on src/types.ts
>    isMonthDisc: boolean;
no debemos usar preposiciones en las variables @lexisgasa

2024-07-18 17:53 UTC, the-refactor-project commented on src/types.ts
>    isMonthDisc: boolean;
Es una regla que solemos aplicar, pero creo que aquí no os queda otra que poner `isDiscOfTheMonth`

2024-07-18 17:53 UTC, the-refactor-project commented on package.json
> +  "main": "public/index.js",
Netlify no ejecuta nada. Quien ejecuta es un browser.

2024-07-19 07:35 UTC, the-refactor-project requested changes

2024-07-19 09:48 UTC, lexisgasa requested changes
El orden.

2024-07-19 10:11 UTC, lexisgasa approved these changes
Ahora veo las propiedades más ordenadas, PR aprobada.

2024-07-19 10:15 UTC, Guiblasco commented on src/types.ts
>  };
ahora si que estan

2024-07-19 10:16 UTC, the-refactor-project approved these changes

2024-07-19 10:16 UTC, merged