Add central container to index.html and style it
Guiblasco/music-oasis-crafters pull request #5
Opened 2024-07-19 16:33 UTC by Guiblasco

- Add a central container at index file
- Style central container
- Add a font family and primary and secondary color at css variable

2024-07-19 16:37 UTC, lexisgasa requested changes

2024-07-19 16:37 UTC, lexisgasa commented on public/styles/styles.css
> +  --secondary-color: #6b7999;
Utilizando YAGNI no debería estar este color todavía.

2024-07-19 16:37 UTC, lexisgasa commented on public/styles/styles.css
> +  font-size: 1.05rem;
A qué se debe poner este font-size en el body?

2024-07-19 16:37 UTC, lexisgasa commented on public/styles/styles.css
> +  font-size: 28px;
Habría que poner los tamaños en unidades relativas.

2024-07-19 16:47 UTC, Guiblasco commented on public/styles/styles.css
> +  font-size: 28px;
correcto

2024-07-19 16:48 UTC, Guiblasco commented on public/styles/styles.css
> +  font-size: 1.05rem;
ouch!

2024-07-20 08:37 UTC, lexisgasa approved these changes
Vale me parece bien ahorita, aprobada.

2024-07-20 08:52 UTC, lexisgasa approved these changes

2024-07-20 08:52 UTC, merged